export const AVATAR_FALLBACK_URL = 'https://api.dicebear.com/7.x/thumbs/png?mouth=variant1'
export const ACTIVE_CHAT_MESSAGES_QUERY = 'active-chat-messages'
export const ACTIVE_CHAT_QUERY = 'active-chat'
export const ACTIVE_PARTICIPANTS_QUERY = 'active-chat-participants'
export const USER_CHATS_QUERY = 'user-chats'
export const GET_CLIENT_QUERY = 'get-client'
export const GET_UNREAD_MSGS = 'unread-messages'
